services:
  tutor-assistant-app-service-postgres:
    image: postgres:16.4-alpine3.20
    container_name: tutor-assistant-app-service-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tutor-assistant-app-service
    volumes:
      - ./data/tutor-assistant-app-service-postgres-data:/var/lib/postgresql/data

  tutor-assistant-keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: tutor-assistant-keycloak
    command: start
    ports:
      - "8100:8080"
    depends_on:
      - tutor-assistant-keycloak-postgres
    environment:
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME=http://localhost:8100
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_DB_URL_HOST=tutor-assistant-keycloak-postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=tutor-assistant-keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password

  tutor-assistant-keycloak-postgres:
    image: postgres:16.4-alpine3.20
    container_name: tutor-assistant-keycloak-postgres
    environment:
      - POSTGRES_DB=tutor-assistant-keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/tutor-assistant-keycloak-postgres-data:/var/lib/postgresql/data

  tutor-assistant-seaweedfs-master:
    image: chrislusf/seaweedfs
    container_name: tutor-assistant-seaweedfs-master
    command: "master"
    ports:
      - "9333:9333"

  tutor-assistant-seaweedfs-volume:
    image: chrislusf/seaweedfs
    container_name: tutor-assistant-seaweedfs-volume
    command: "volume -mserver tutor-assistant-seaweedfs-master:9333 -dir /data -publicUrl localhost:8200"
    ports:
      - "8200:8080"
    volumes:
      - ./data/tutor-assistant-seaweedfs-volume-data:/data
